/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ltp.unidade08.view;

import java.util.List;
import javax.swing.JOptionPane;
import ltp.unidade08.control.Agencia;
import ltp.unidade08.model.BancoException;

/**
 *
 * @author Bruno
 */
public class FrmCadastro extends javax.swing.JFrame {

    /**
     * Creates new form FrmCadastro
     */
    public FrmCadastro() {
        initComponents();
        
        lblNumeroConta.setText("Número da conta: " + Agencia.getProximaConta());
        
        List<Integer> agencias = Principal.banco.retornarNumeroAgencias();
        for(int i : agencias){
           cmbAgencias.addItem("Agência " + i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblTipoConta = new javax.swing.JLabel();
        radCorrente = new javax.swing.JRadioButton();
        radPoupanca = new javax.swing.JRadioButton();
        lblTitularConta = new javax.swing.JLabel();
        txtTitular = new javax.swing.JTextField();
        lblTitularAgencia = new javax.swing.JLabel();
        cmbAgencias = new javax.swing.JComboBox<>();
        lblSenha = new javax.swing.JLabel();
        lblNumeroConta = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Banco LTP S.A.");

        lblTipoConta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipoConta.setText("Tipo de Conta:");

        buttonGroup1.add(radCorrente);
        radCorrente.setSelected(true);
        radCorrente.setText("C. Corrente");
        radCorrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radCorrenteActionPerformed(evt);
            }
        });

        buttonGroup1.add(radPoupanca);
        radPoupanca.setText("C. Poupança");

        lblTitularConta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitularConta.setText("Títular da Conta:");

        lblTitularAgencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitularAgencia.setText("Agência da Conta:");

        lblSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSenha.setText("Senha da Conta:");

        lblNumeroConta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumeroConta.setText("Número da Conta:");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTipoConta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTitularAgencia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(radCorrente)
                        .addGap(32, 32, 32)
                        .addComponent(radPoupanca)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(lblTitularConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblNumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(lblSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSenha)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(txtTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cmbAgencias, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblTipoConta)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radCorrente)
                    .addComponent(radPoupanca))
                .addGap(27, 27, 27)
                .addComponent(lblTitularAgencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbAgencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNumeroConta)
                .addGap(18, 18, 18)
                .addComponent(lblTitularConta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(lblSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalvar)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radCorrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radCorrenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radCorrenteActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        int tipo = radCorrente.isSelected() ? 1 : 2;
        String titular = txtTitular.getText();
        String senha = txtSenha.getText();
        int agencia = Integer.parseInt(cmbAgencias.getSelectedItem().toString().replace("Agência ", ""));
        
        try{
            boolean sucesso = Principal.banco.cadastrarConta(tipo, agencia, titular, senha);
            if(sucesso){
                JOptionPane.showMessageDialog(this, "Cliente salvo com sucesso.", "Cadastro", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(this, "Não foi possível concluir o cadastro.", "Erro.", JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(BancoException bex){
            JOptionPane.showMessageDialog(this, bex.getMessage(), "Erro.", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbAgencias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblNumeroConta;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTipoConta;
    private javax.swing.JLabel lblTitularAgencia;
    private javax.swing.JLabel lblTitularConta;
    private javax.swing.JRadioButton radCorrente;
    private javax.swing.JRadioButton radPoupanca;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtTitular;
    // End of variables declaration//GEN-END:variables
}
